# Country equity data for GCR-ABM
# OECD status and historical cumulative CO2 emissions (1850-2023, GtCO2)

COUNTRY_EQUITY_DATA = {
    # Tier 1: High GDP economies
    "USA": {"oecd": True, "historical_emissions_gtco2": 420},
    "China": {"oecd": False, "historical_emissions_gtco2": 280},
    "Japan": {"oecd": True, "historical_emissions_gtco2": 70},
    "Germany": {"oecd": True, "historical_emissions_gtco2": 95},
    "UK": {"oecd": True, "historical_emissions_gtco2": 80},
    "France": {"oecd": True, "historical_emissions_gtco2": 45},
    "India": {"oecd": False, "historical_emissions_gtco2": 60},
    "Italy": {"oecd": True, "historical_emissions_gtco2": 25},
    "Canada": {"oecd": True, "historical_emissions_gtco2": 35},
    "South Korea": {"oecd": True, "historical_emissions_gtco2": 18},
    "Australia": {"oecd": True, "historical_emissions_gtco2": 20},
    "Spain": {"oecd": True, "historical_emissions_gtco2": 15},

    # Tier 2: Medium GDP economies
    "Brazil": {"oecd": False, "historical_emissions_gtco2": 25},
    "Mexico": {"oecd": True, "historical_emissions_gtco2": 18},
    "Indonesia": {"oecd": False, "historical_emissions_gtco2": 22},
    "Netherlands": {"oecd": True, "historical_emissions_gtco2": 20},
    "Saudi Arabia": {"oecd": False, "historical_emissions_gtco2": 14},
    "Turkey": {"oecd": True, "historical_emissions_gtco2": 12},
    "Switzerland": {"oecd": True, "historical_emissions_gtco2": 4},
    "Poland": {"oecd": True, "historical_emissions_gtco2": 25},
    "Argentina": {"oecd": False, "historical_emissions_gtco2": 8},
    "Sweden": {"oecd": True, "historical_emissions_gtco2": 6},
    "Belgium": {"oecd": True, "historical_emissions_gtco2": 12},
    "Thailand": {"oecd": False, "historical_emissions_gtco2": 7},
    "Nigeria": {"oecd": False, "historical_emissions_gtco2": 4},
    "Austria": {"oecd": True, "historical_emissions_gtco2": 8},
    "Norway": {"oecd": True, "historical_emissions_gtco2": 5},
    "UAE": {"oecd": False, "historical_emissions_gtco2": 3},
    "Israel": {"oecd": True, "historical_emissions_gtco2": 2},
    "Singapore": {"oecd": False, "historical_emissions_gtco2": 1},
    "Malaysia": {"oecd": False, "historical_emissions_gtco2": 5},
    "Philippines": {"oecd": False, "historical_emissions_gtco2": 4},
    "South Africa": {"oecd": False, "historical_emissions_gtco2": 18},
    "Colombia": {"oecd": False, "historical_emissions_gtco2": 5},
    "Denmark": {"oecd": True, "historical_emissions_gtco2": 7},

    # Tier 3: Lower GDP / Developing economies
    "Kenya": {"oecd": False, "historical_emissions_gtco2": 0.5},
    "Vietnam": {"oecd": False, "historical_emissions_gtco2": 4},
    "Bangladesh": {"oecd": False, "historical_emissions_gtco2": 2},
    "Egypt": {"oecd": False, "historical_emissions_gtco2": 6},
    "Pakistan": {"oecd": False, "historical_emissions_gtco2": 4},
    "Chile": {"oecd": True, "historical_emissions_gtco2": 4},
    "Peru": {"oecd": False, "historical_emissions_gtco2": 3},
    "Czech Republic": {"oecd": True, "historical_emissions_gtco2": 18},
    "Romania": {"oecd": False, "historical_emissions_gtco2": 10},
    "New Zealand": {"oecd": True, "historical_emissions_gtco2": 2},
    "Portugal": {"oecd": True, "historical_emissions_gtco2": 4},
    "Greece": {"oecd": True, "historical_emissions_gtco2": 6},
    "Iraq": {"oecd": False, "historical_emissions_gtco2": 5},
    "Kazakhstan": {"oecd": False, "historical_emissions_gtco2": 12},
    "Morocco": {"oecd": False, "historical_emissions_gtco2": 2},
    "Ethiopia": {"oecd": False, "historical_emissions_gtco2": 0.4},
    "Ghana": {"oecd": False, "historical_emissions_gtco2": 0.8},
    "Tanzania": {"oecd": False, "historical_emissions_gtco2": 0.5},
    "Uganda": {"oecd": False, "historical_emissions_gtco2": 0.3},
}
